version: '3.8'
services:
    app:
      build: ./webserver
      container_name: app
      restart: always
      volumes:
        - ./certs:/etc/nginx/certs
      ports:
      - 8081:80
      - 443:443